version: "3.4"
services:
  nginx:
    container_name: "nginx"
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/.htpasswd:/etc/nginx/.htpasswd"
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - /home/sysadmin/certificates:/etc/nginx/conf.d/certificates
    depends_on:
      - streamlit
    restart: always

  streamlit:
    container_name: "streamlit"
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000