version: "3.4"
services:
  nginx:
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    build:
      context: /home/centos
      dockerfile: ./NoStream/nginx/Dockerfile
    depends_on:
      - streamlit
    restart: always

  streamlit:
    container_name: "streamlit"
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    restart: always
    ports:
      - 8501:8501
    command: streamlit run ./streamlit/streamlit_app.py --server.port 8501

  streamlit_compact:
    container_name: "streamlit_compact"
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    restart: always
    ports:
      - 8502:8502
    command: streamlit run ./streamlit/streamlit_app_compact.py --server.port 8502
