version: "3.4"
services:
  nginx:
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ~/certificates:/etc/nginx/conf.d/certificates
    depends_on:
      - streamlit
    restart: always

  streamlit:
    container_name: "streamlit"
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    restart: always
    ports:
      - 8501:8501
