name: streamlit
channels:
  - conda-forge
  - plotly
  - anaconda
dependencies:
  - python=3.6   # or 2.7
  - glpk
  - numpy
  - pandas=1.3.5
  - openpyxl
  - mathjax
  - plotly
  - glpk=0.4.6
  - kaleido
  - pip
  - pip:
    - streamlit
    - pyomo==6.3.0