name: streamlit
channels:
  - conda-forge
  - plotly
  - anaconda
dependencies:
  - python=3.6   # or 2.7
  - pip
  - numpy
  - pandas
  - openpyxl
  - pip:
    - streamlit
    - pyomo==6.3.0
  - glpk
  - plotly
  - mathjax
  - python-kaleido
