name: no-stream
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - glpk
  - pip:
      - numpy
      - pandas
      - openpyxl
      - streamlit
      - pyutilib
      - plotly
      - pyomo
      - google-api-python-client
      - oauth2client
